language: cpp
sudo: required

before_install:
  - export GCC="$GCC -m64 -fPIC -DPIC" GXX="$GXX -m64 -fPIC -DPIC"
  - pushd $HOME/build
  - git clone https://github.com/DX-MON/crunch.git DX-MON/crunch
  - cd DX-MON/crunch
  - sudo make install
  - popd
install:
  - make
script:
  - make tests
  - make check
after_success:
  - if [ "$COVERAGE" == "1" ]; then
      bash <(curl -s https://codecov.io/bash) -x $GCOV;
    fi

matrix:
  include:
    - compiler: clang-4.0
      env: GCC=clang-4.0 GXX=clang++-4.0 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - llvm-4.0
            - clang-4.0
    - compiler: clang-4.0
      env: GCC=clang-4.0 GXX=clang++-4.0 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - clang-4.0
            - llvm-4.0
    - compiler: clang-5.0
      env: GCC=clang-5.0 GXX=clang++-5.0 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - clang-5.0
            - llvm-5.0
    - compiler: clang-5.0
      env: GCC=clang-5.0 GXX=clang++-5.0 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - clang-5.0
            - llvm-5.0
    - compiler: clang-6.0
      env: GCC=clang-6.0 GXX=clang++-6.0 GCOV='llvm-cov gcov'
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - clang-6.0
            - llvm-6.0
    - compiler: clang-6.0
      env: GCC=clang-6.0 GXX=clang++-6.0 COVERAGE=0
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - clang-6.0
            - llvm-6.0
    - compiler: gcc-5
      env: GCC=gcc-5 GXX=g++-5 GCOV=gcov-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
    - compiler: gcc-5
      env: GCC=gcc-5 GXX=g++-5 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
    - compiler: gcc-6
      env: GCC=gcc-6 GXX=g++-6 GCOV=gcov-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
    - compiler: gcc-6
      env: GCC=gcc-6 GXX=g++-6 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
    - compiler: gcc-7
      env: GCC=gcc-7 GXX=g++-7 GCOV=gcov-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
    - compiler: gcc-7
      env: GCC=gcc-7 GXX=g++-7 COVERAGE=0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
    - compiler: gcc-8
      env: GCC=gcc-8 GXX=g++-8 GCOV=gcov-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8

env:
  global:
    - COVERAGE=1
