language: cpp

before_install:
  - export GCC="$GCC -m64 -fPIC -DPIC" GXX="$GXX -m64 -fPIC -DPIC"
install:
script:
  - make
  - make tests
  - make check

matrix:
  include:
    - compiler: clang-3.8
      env: GCC=clang GXX=clang++
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise main'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - clang-3.8
    - compiler: clang-3.9
      env: GCC=clang GXX=clang++
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.9 main'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - clang-3.9
    - compiler: gcc-4.9
      env: GCC=gcc-4.9 GXX=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
    - compiler: gcc-5
      env: GCC=gcc-5 GXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
    - compiler: gcc-6
      env: GCC=gcc-6 GXX=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
